### ISSUE TITLE
Add removal of old indexed blocks to the indexer

### ISSUE THREAD

**Issue by abukosek** [oasisprotocol/oasis-web3-gateway#2]
There should be some way of (automatically) deleting old indexed blocks to prevent the database from filling up.

A config option should be added to specify the age limit of blocks.  Then periodic checks should be made to delete blocks older than the specified age limit.

There might be a better way to implement this (I can't remember if postgresql supports setting expiry time on rows or not), so feel free to use that if it's faster :)

**Comment by anonymousGiga** [comment]
Thanks，we'll add this feature later.

**Comment by anonymousGiga** [comment]
The scheme as follows:
1. A configuration switch determines whether the purging function is turned on. Because there is not much data stored in the web3gateway, this configuration switch is turned off by default;

2. When the purning function is turned on, given a configuration parameter history_step, the block related data with blockNumber < (latest - history_step) will be deleted through periodic inspection, but the transaction will not be deleted.

Can you give some advice?

**Comment by kostko** [comment]
1. Right.
2. Yes, although I don't see any reason why we wouldn't delete transaction data outside the retention window as well? I believe everything should be pruned if configured to do so.

**Comment by anonymousGiga** [comment]
We believe that eth trading may be used more frequently and more likely to use the history of earlier events, so we want to keep the trading history. But as you said, we can delete all the history because we have made the configuration.  So we will do it in the way you say.

**Comment by kostko** [comment]
Yeah in that case people should either disable pruning or set a large enough window.
